/* !!! Generated by ax_common.cmake */ 

#include "AxUnitTest.h"

void AxCore_Test_Base() {
    AX_TEST_FUNC(Test_BasicType)
    AX_TEST_FUNC(Test_Enum)
    AX_TEST_FUNC(Test_HashInt)
    AX_TEST_FUNC(Test_Math)
    AX_TEST_FUNC(Test_Uuid)
}
