/* !!! Generated by ax_common.cmake */ 

#include "AxUnitTest.h"

void AxPlatform_Test() {
    AX_TEST_GROUP(AxPlatform_Test_Base)
    AX_TEST_GROUP(AxPlatform_Test_Container)
    AX_TEST_GROUP(AxPlatform_Test_Pointer)
    AX_TEST_GROUP(AxPlatform_Test_String)
}
