/* !!! Generated by ax_common.cmake - ax_gen_test_all_cpp */ 

#include "AxUnitTest.h"
import AxCore.UnitTest;

void AxCore_Test_Base() {
    AX_TEST_FUNC(Test_BasicType)
    AX_TEST_FUNC(Test_Enum)
    AX_TEST_FUNC(Test_HashInt)
    AX_TEST_FUNC(Test_Math)
    AX_TEST_FUNC(Test_Uuid)
}

void AxCore_Test_Container() {
    AX_TEST_FUNC(Test_Dict)
    AX_TEST_FUNC(Test_LinkedList)
}

void AxCore_Test_Math() {
    AX_TEST_FUNC(Test_Vec)
}

void AxCore_Test_Pointer() {
    AX_TEST_FUNC(Test_SPtr)
}

void AxCore_Test_Rtti() {
    AX_TEST_FUNC(Test_Rtti)
}

void AxCore_Test_String() {
    AX_TEST_FUNC(Test_Format)
    AX_TEST_FUNC(Test_String)
}

void AxCore_Test() {
    AX_TEST_GROUP(AxCore_Test_Base)
    AX_TEST_GROUP(AxCore_Test_Container)
    AX_TEST_GROUP(AxCore_Test_Math)
    AX_TEST_GROUP(AxCore_Test_Pointer)
    AX_TEST_GROUP(AxCore_Test_Rtti)
    AX_TEST_GROUP(AxCore_Test_String)
}

