/* !!! Generated by ax_common.cmake */ 

#include "AxUnitTest.h"

void AxCore_Test() {
    AX_TEST_GROUP(AxCore_Test_Base)
    AX_TEST_GROUP(AxCore_Test_Pointer)
    AX_TEST_GROUP(AxCore_Test_String)
}
