module;
//========================================================//
//       This file is generated by AxCppHeaderTool        //
//========================================================//

module AxEngine;
import :SceneEntity;

AxEngine::SceneComponent::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("SceneComponent");
}; 

AxEngine::SceneEntity::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("SceneEntity");
}; 

AxEngine::MeshRendererComponent::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("MeshRendererComponent");
}; 

AxEngine::LightComponent::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("LightComponent");
}; 

AxEngine::CameraComponent::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("CameraComponent");
}; 

AxEngine::SceneWorld::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("SceneWorld");
}; 

