module;
//========================================================//
//       This file is generated by AxCppHeaderTool        //
//========================================================//

module AxEngine;
import :SceneEntity;

AxEngine::SceneComponent::MutRttiInit::MutRttiInit() {
	ownFields.ensureCapacity(0);
}; 

AxEngine::SceneEntity::MutRttiInit::MutRttiInit() {
	ownFields.ensureCapacity(0);
}; 

AxEngine::SceneWorld::MutRttiInit::MutRttiInit() {
	ownFields.ensureCapacity(0);
}; 

AxEngine::MeshRendererComponent::MutRttiInit::MutRttiInit() {
	ownFields.ensureCapacity(0);
}; 

AxEngine::MeshRendererSystem::MutRttiInit::MutRttiInit() {
	ownFields.ensureCapacity(0);
}; 

