#pragma once
//========================================================//
//       This file is generated by AxCppHeaderTool        //
//========================================================//


//--- Type AxEngine::SceneComponent ----------
#define AX_GENERATED_BODY_LINE12() \
	AX_RTTI_INFO(SceneComponent, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::SceneEntity ----------
#define AX_GENERATED_BODY_LINE17() \
	AX_RTTI_INFO(SceneEntity, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::CTransform ----------
#define AX_GENERATED_BODY_LINE41() \
	AX_RTTI_INFO(CTransform, SceneComponent) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::CMeshRenderer ----------
#define AX_GENERATED_BODY_LINE50() \
	AX_RTTI_INFO(CMeshRenderer, SceneComponent) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------

