#pragma once
//========================================================//
//       This file is generated by AxCppHeaderTool        //
//========================================================//


//--- Type AxEngine::SceneComponent ----------
#define AX_GENERATED_BODY_LINE14() \
	AX_RTTI_INFO(SceneComponent, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::SceneEntity ----------
#define AX_GENERATED_BODY_LINE19() \
	AX_RTTI_INFO(SceneEntity, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::SceneWorld ----------
#define AX_GENERATED_BODY_LINE71() \
	AX_RTTI_INFO(SceneWorld, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::CMeshRenderer ----------
#define AX_GENERATED_BODY_LINE86() \
	AX_RTTI_INFO(CMeshRenderer, SceneComponent) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::CMeshRendererSystem ----------
#define AX_GENERATED_BODY_LINE101() \
	AX_RTTI_INFO(CMeshRendererSystem, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------

