#pragma once
//========================================================//
//       This file is generated by AxCppHeaderTool        //
//========================================================//


//--- Type AxEngine::SceneComponent ----------
#define AX_GENERATED_BODY_LINE60() \
	AX_RTTI_INFO(SceneComponent, Object) \
public:\
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
private:\
//------


//--- Type AxEngine::SceneEntity ----------
#define AX_GENERATED_BODY_LINE90() \
	AX_RTTI_INFO(SceneEntity, Object) \
public:\
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
private:\
//------


//--- Type AxEngine::MeshRendererComponent ----------
#define AX_GENERATED_BODY_LINE185() \
	AX_RTTI_INFO(MeshRendererComponent, SceneComponent) \
public:\
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
private:\
//------


//--- Type AxEngine::LightComponent ----------
#define AX_GENERATED_BODY_LINE208() \
	AX_RTTI_INFO(LightComponent, SceneComponent) \
public:\
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
private:\
//------


//--- Type AxEngine::SceneWorld ----------
#define AX_GENERATED_BODY_LINE223() \
	AX_RTTI_INFO(SceneWorld, Object) \
public:\
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
private:\
//------

