module;
//========================================================//
//       This file is generated by AxCppHeaderTool        //
//========================================================//

module AxEngine;
import :SceneEntity;

AxEngine::SceneComponent::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("SceneComponent");
}; 

AxEngine::SceneEntity::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("SceneEntity");
}; 

AxEngine::SceneWorld::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("SceneWorld");
}; 

AxEngine::MeshRendererComponent::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("MeshRendererComponent");
}; 

AxEngine::MeshRendererSystem::MutRttiInit::MutRttiInit() {
	name = NameId::s_make("MeshRendererSystem");
}; 

