#pragma once
//========================================================//
//       This file is generated by AxCppHeaderTool        //
//========================================================//


//--- Type AxEngine::SceneComponent ----------
#define AX_GENERATED_BODY_LINE15() \
	AX_RTTI_INFO(SceneComponent, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::SceneEntity ----------
#define AX_GENERATED_BODY_LINE40() \
	AX_RTTI_INFO(SceneEntity, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::SceneWorld ----------
#define AX_GENERATED_BODY_LINE116() \
	AX_RTTI_INFO(SceneWorld, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::MeshRendererComponent ----------
#define AX_GENERATED_BODY_LINE137() \
	AX_RTTI_INFO(MeshRendererComponent, SceneComponent) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------


//--- Type AxEngine::MeshRendererSystem ----------
#define AX_GENERATED_BODY_LINE151() \
	AX_RTTI_INFO(MeshRendererSystem, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit();\
	}; \
//------

