module;

module AxCppHeaderTool;
import :Generator;

namespace ax::AxCppHeaderTool {

Generator::Generator() {
}

void Generator::gen(CmdOptions& opt, StrView srcFilename) {
	_parser.readFile(srcFilename, _typeDB);

	if (!_typeDB.types.size()) {
		return;
	}

	auto headerMessage = StrLit("//========================================================//\n"
								"//       This file is generated by AxCppHeaderTool        //\n"
								"//========================================================//\n"
								"\n");

	_outHeader = "#pragma once\n";
	_outHeader.append(headerMessage);
	
	_outCpp = "module;\n";
	_outCpp.append(headerMessage);
	_outCpp.append("module AxEngine;\n");

	for (auto& type : _typeDB.types.values()) {
		gen_type(srcFilename, type);
	}

	// auto basename = FilePath::basename(filename, true);
	// TempString outFilename(opt.outPath, "/", basename, ".gen.h");
	auto outHeaderFilename = FilePath::changeExtension(srcFilename, "gen.h");
	File::writeFileIfChanged(outHeaderFilename, _outHeader, opt.writeFileOpt);
	
	auto outCppFilename = FilePath::changeExtension(srcFilename, "gen.cpp");
	File::writeFileIfChanged(outCppFilename, _outCpp, opt.writeFileOpt);
}

void Generator::gen_type(StrView srcFilename, TypeInfo& type) {
	if (type.lineNumber_AX_GENERATED_BODY == 0) {
		throw Error_Runtime(Fmt("missing AX_GENERATED_BODY in type [{}]\n  filename={}", 
									type.fullname, srcFilename));
	}
	_outHeader.appendFormat(    "\n//--- Type {} ----------\n", type.fullname);
	_outHeader.appendFormat(    "#define AX_GENERATED_BODY_LINE{}() \\\n", type.lineNumber_AX_GENERATED_BODY);
	_outHeader.appendFormat(    "\t""AX_RTTI_INFO({}, {}) \\\n", type.name, type.baseName);
	_outHeader.appendFormat(    "\t""struct MutRttiInit; \\\n");
	
	// _outStr.appendFormat(    "\t""struct MutRttiInit : public MutRtti {{ \\\n");
	// _outStr.appendFormat(    "\t\t""MutRttiInit() {{ \\\n");
	// _outStr.appendFormat(    "\t\t\t""ownFields.ensureCapacity({}); \\\n", type.props.size());
	// for (auto &prop : type.props.values()) {
	// 	_outStr.appendFormat("\t\t\t""addField(\"{}\", &This::{}); \\\n",
	// 	                     prop.name, prop.name);
	// }
	// _outStr.appendFormat(    "\t\t""}}; \\\n");
	// _outStr.appendFormat(    "\t""}}; \\\n");
	_outHeader.appendFormat(    "//------\n\n");
	_outHeader << "\n";
}

} //namespace