module;

module AxCppHeaderTool;
import :Generator;

namespace ax::AxCppHeaderTool {

Generator::Generator() {
}

void Generator::gen(CmdOptions& opt, StrView srcFilename) {
	_parser.readFile(srcFilename, _typeDB);

	if (!_typeDB.types.size()) {
		return;
	}

	auto headerMessage = StrLit("//========================================================//\n"
								"//       This file is generated by AxCppHeaderTool        //\n"
								"//========================================================//\n"
								"\n");

	_outHeader = "#pragma once\n";
	_outHeader.append(headerMessage);
	
	_outCpp = "module;\n";
	_outCpp.append(headerMessage);
	_outCpp.appendFormat("module {};\n", _parser.module());
	_outCpp.appendFormat("import :{};\n\n", _parser.modulePartition());
	
	for (auto& type : _typeDB.types.values()) {
		gen_type(srcFilename, type);
	}

	auto basename = FilePath::basename(srcFilename, true);
	auto outTest = Fmt("{}-gen.h", basename);
	
	auto srcFilenameWithoutExt = FilePath::changeExtension(srcFilename, "");
	auto outHeaderFilename = Fmt("{}-gen.h", srcFilenameWithoutExt);
	File::writeFileIfChanged(outHeaderFilename, _outHeader, opt.writeFileOpt);
	
	auto outCppFilename = Fmt("{}-gen.cpp", srcFilenameWithoutExt);
	File::writeFileIfChanged(outCppFilename, _outCpp, opt.writeFileOpt);
}

void Generator::gen_type(StrView srcFilename, TypeInfo& type) {
	if (type.lineNumber_AX_GENERATED_BODY == 0) {
		throw Error_Runtime(Fmt("missing AX_GENERATED_BODY in type [{}]\n  filename={}", 
									type.fullname, srcFilename));
	}
	_outHeader.appendFormat("\n//--- Type {} ----------\n", type.fullname);
	_outHeader.appendFormat("#define AX_GENERATED_BODY_LINE{}() \\\n", type.lineNumber_AX_GENERATED_BODY);
	_outHeader.appendFormat("\t""AX_RTTI_INFO({}, {}) \\\n", type.name, type.baseName);
	_outHeader.appendFormat("public:\\\n");
	_outHeader.appendFormat("\t""struct MutRttiInit : public MutRtti {{ \\\n");
	_outHeader.appendFormat("\t\t""MutRttiInit();\\\n");
	_outHeader.appendFormat("\t""}}; \\\n");
	_outHeader.appendFormat("private:\\\n");
	_outHeader.appendFormat("//------\n\n");
	
//	_outCpp.appendFormat("{}\n", type.openNamespaceScope);
	_outCpp.appendFormat("{}::MutRttiInit::MutRttiInit() {{\n", type.fullname);
	{
		_outCpp.appendFormat("\t" "name = NameId::s_make(\"{}\");\n", type.name);
	
		if (type.props.size() > 0) {
			_outCpp.appendFormat("\t" "ownFields.ensureCapacity({});\n", type.props.size());
		}
	
		for (auto &prop : type.props.values()) {
			_outCpp.appendFormat("\t" "addField(\"{}\", &This::{});\n",
								 prop.name, prop.name);
		}
	}
	_outCpp.appendFormat("}}; \n\n");
	
//	_outCpp.appendFormat("{}\n\n", type.closeNamespaceScope);

}

} //namespace