#ifndef __AX_HLSL_CPU_COMMON_h__
#define __AX_HLSL_CPU_COMMON_h__

#define AX_HLSL_MESH_SHADER_MAX_VERTEX_COUNT	128U
#define AX_HLSL_MESH_SHADER_MAX_PRIM_COUNT		128U
#define AX_HLSL_THREADS_PER_WAVE				32U


#endif // __AX_HLSL_CPU_COMMON_h__