/* !!! Generated by ax_common.cmake - ax_gen_test_all_cpp */ 

#include "AxUnitTest.h"
import AxCore.UnitTest;

void AxCore_Test_File_Test_File_Example_SubDir() {
}

void AxCore_Test_File_Test_File_Example() {
    AX_TEST_GROUP(AxCore_Test_File_Test_File_Example_SubDir)
}

void AxCore_Test_Base() {
    AX_TEST_FUNC(Test_BasicType)
    AX_TEST_FUNC(Test_HashInt)
    AX_TEST_FUNC(Test_Math)
    AX_TEST_FUNC(Test_Scoped)
    AX_TEST_FUNC(Test_StructUtil)
    AX_TEST_FUNC(Test_Uuid)
}

void AxCore_Test_Container() {
    AX_TEST_FUNC(Test_Array)
    AX_TEST_FUNC(Test_Dict)
    AX_TEST_FUNC(Test_LinkedList)
}

void AxCore_Test_Data() {
    AX_TEST_FUNC(Test_Json)
}

void AxCore_Test_File() {
    AX_TEST_FUNC(Test_File)
    AX_TEST_GROUP(AxCore_Test_File_Test_File_Example)
}

void AxCore_Test_Math() {
    AX_TEST_FUNC(Test_Vec)
}

void AxCore_Test_Other() {
    AX_TEST_FUNC(Test_Enum)
}

void AxCore_Test_Pointer() {
    AX_TEST_FUNC(Test_SPtr)
}

void AxCore_Test_Rtti() {
    AX_TEST_FUNC(Test_Rtti)
}

void AxCore_Test_String() {
    AX_TEST_FUNC(Test_Format)
    AX_TEST_FUNC(Test_String)
}

void AxCore_Test_Time() {
    AX_TEST_FUNC(Test_DateTime)
}

void AxCore_Test() {
    AX_TEST_GROUP(AxCore_Test_Base)
    AX_TEST_GROUP(AxCore_Test_Container)
    AX_TEST_GROUP(AxCore_Test_Data)
    AX_TEST_GROUP(AxCore_Test_File)
    AX_TEST_GROUP(AxCore_Test_Math)
    AX_TEST_GROUP(AxCore_Test_Other)
    AX_TEST_GROUP(AxCore_Test_Pointer)
    AX_TEST_GROUP(AxCore_Test_Rtti)
    AX_TEST_GROUP(AxCore_Test_String)
    AX_TEST_GROUP(AxCore_Test_Time)
}

