module;

module AxCppHeaderTool;
import :Generator;

namespace ax::AxCppHeaderTool {

Generator::Generator() {
}

void Generator::gen(CmdOptions& opt, StrView srcFilename) {
	_parser.readFile(srcFilename, _typeDB);

	if (!_typeDB.types.size()) {
		return;
	}

	auto headerMessage = StrLit("#pragma once\n"
								"//==============================================================//\n"
								"//                                                              //\n"
								"//       This file is generated by AxCppHeaderTool              //\n"
								"//                                                              //\n"
								"//==============================================================//\n"
								"\n");

								
	_outStr = headerMessage;

	for (auto& type : _typeDB.types.values()) {
		gen_type(srcFilename, type);
	}

	// auto basename = FilePath::basename(filename, true);
	// TempString outFilename(opt.outPath, "/", basename, ".gen.h");
	auto outFilename = FilePath::changeExtension(srcFilename, "gen.h");
	File::writeFileIfChanged(outFilename, _outStr, opt.writeFileOpt);
}

void Generator::gen_type(StrView srcFilename, TypeInfo& type) {
	if (type.lineNumber_AX_GENERATED_BODY == 0) {
		throw Error_Runtime(Fmt("missig AX_GENERATED_BODY in type [{}]\n  filename={}", 
									type.fullname, srcFilename));
	}
	
	_outStr.appendFormat(    "\n//--- Type {} ----------\n", type.fullname);
	_outStr.appendFormat(    "#define AX_GENERATED_BODY_LINE{}() \\\n", type.lineNumber_AX_GENERATED_BODY);
	_outStr.appendFormat(    "\t""AX_RTTI_INFO({}, {}) \\\n", type.name, type.baseName);
	_outStr.appendFormat(    "\t""struct MutRttiInit : public MutRtti {{ \\\n");
	_outStr.appendFormat(    "\t\t""MutRttiInit() {{ \\\n");
	_outStr.appendFormat(    "\t\t\t""ownFields.ensureCapacity({}); \\\n", type.props.size());
	for (auto &prop : type.props.values()) {
		_outStr.appendFormat("\t\t\t""addField(\"{}\", &_TYPE_INFO_This::{}); \\\n",
		                     prop.typeName,
		                     prop.name,
		                     prop.name);
	}
	_outStr.appendFormat(    "\t\t""}}; \\\n");
	_outStr.appendFormat(    "\t""}}; \\\n");
	_outStr.appendFormat(    "//------\n\n");
	_outStr << "\n";
}

} //namespace