#pragma once
//==============================================================//
//                                                              //
//       This file is generated by AxCppHeaderTool              //
//                                                              //
//==============================================================//


//--- Type AxEngine::SceneComponent ----------
#define AX_GENERATED_BODY_LINE12() \
  AX_RTTI_INFO(SceneComponent, Object) \
//------



//--- Type AxEngine::SceneEntity ----------
#define AX_GENERATED_BODY_LINE17() \
  AX_RTTI_INFO(SceneEntity, Object) \
//------



//--- Type AxEngine::RenderMeshComponent ----------
#define AX_GENERATED_BODY_LINE41() \
  AX_RTTI_INFO(RenderMeshComponent, SceneComponent) \
//------


