#pragma once
//==============================================================//
//                                                              //
//       This file is generated by AxCppHeaderTool              //
//                                                              //
//==============================================================//


//--- Type AxEngine::SceneComponent ----------
#define AX_GENERATED_BODY_LINE12() \
	AX_RTTI_INFO(SceneComponent, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit() { \
			ownFields.ensureCapacity(0); \
		}; \
	}; \
//------



//--- Type AxEngine::SceneEntity ----------
#define AX_GENERATED_BODY_LINE17() \
	AX_RTTI_INFO(SceneEntity, Object) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit() { \
			ownFields.ensureCapacity(0); \
		}; \
	}; \
//------



//--- Type AxEngine::TransformComponent ----------
#define AX_GENERATED_BODY_LINE41() \
	AX_RTTI_INFO(TransformComponent, SceneComponent) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit() { \
			ownFields.ensureCapacity(3); \
			addField("position", &This::position); \
			addField("rotation", &This::rotation); \
			addField("scale", &This::scale); \
		}; \
	}; \
//------



//--- Type AxEngine::RenderMeshComponent ----------
#define AX_GENERATED_BODY_LINE50() \
	AX_RTTI_INFO(RenderMeshComponent, SceneComponent) \
	struct MutRttiInit : public MutRtti { \
		MutRttiInit() { \
			ownFields.ensureCapacity(0); \
		}; \
	}; \
//------


